Armbench metric dict
tensorleap/tensorleap pull request #66
Opened 2023-08-09 06:48 UTC by RanHomri

modify metrics and metadata calculation to dictionary

2023-08-09 13:51 UTC, Chen-Roth reviewed
Change also in the readme file from cli-go to leap-cli in all places (: 
LSTM

2023-08-09 13:51 UTC, Chen-Roth commented on examples/armbench-segmentation/leap.yaml
add also object_detection.yml

2023-08-13 07:55 UTC, yotamazriel requested changes

2023-08-13 07:55 UTC, yotamazriel commented on examples/armbench-segmentation/armbench_segmentation/metrics.py
> +        if len(ioas) > 0:
What is `ioas`?

2023-08-13 07:55 UTC, yotamazriel commented on examples/armbench-segmentation/leap_binder.py
> +    return res
Why are we doing it?

2023-08-13 07:55 UTC, yotamazriel commented on examples/armbench-segmentation/leap_binder.py
> +    return res
This way, we are calculating many calculations four times; let's get into those functions and make sure we run efficiently.

2023-08-13 07:55 UTC, yotamazriel commented on examples/armbench-segmentation/leap_binder.py
> +    return res
Same here

2023-08-13 07:55 UTC, yotamazriel commented on examples/armbench-segmentation/leap_binder.py
> -leap_binder.set_metadata(get_obj_bbox_occlusions_avg, DatasetMetadataType.int, "avg_obj_bbox_occlusions")
Nice!

2023-08-16 16:50 UTC, closed without merging